DROP TABLE IF EXISTS DEPENDENTE;
DROP TABLE IF EXISTS TRABALHA_EM;
DROP TABLE IF EXISTS PROJETO;
DROP TABLE IF EXISTS LOCALIZACOES_DEP;
DROP TABLE IF EXISTS DEPARTAMENTO;
DROP TABLE IF EXISTS FUNCIONARIO;

CREATE TABLE FUNCIONARIO (
    Pnome VARCHAR,
    Minicial CHAR(1),
    Unome VARCHAR,
    Cpf CHAR(11) UNIQUE NOT NULL,
    Datanasc DATE,
    Endereco VARCHAR,
    Sexo CHAR(1),
    Salario DECIMAL(10,3),
    Cpf_supervisor CHAR(11) NOT NULL,
    Dnr INT,
    PRIMARY KEY(Cpf),
    FOREIGN KEY(Cpf_supervisor) REFERENCES FUNCIONARIO(Cpf)
);

CREATE TABLE DEPARTAMENTO (
    Dnome VARCHAR,
    Dnumero INT NOT NULL,
    Cpf_gerente CHAR(11) UNIQUE NOT NULL,
    Data_inicio_gerente DATE,
    PRIMARY KEY(Dnumero),
    FOREIGN KEY(Cpf_gerente) REFERENCES FUNCIONARIO(Cpf)
);

ALTER TABLE FUNCIONARIO 
ADD FOREIGN KEY(Dnr) REFERENCES DEPARTAMENTO(Dnumero);

CREATE TABLE LOCALIZACOES_DEP (
    Dnumero INT NOT NULL,
    Dlocal VARCHAR NOT NULL,
    PRIMARY KEY(Dlocal, Dnumero),
    FOREIGN KEY(Dnumero) REFERENCES DEPARTAMENTO(Dnumero)
);

CREATE TABLE PROJETO (
    Projnome VARCHAR,
    Projnumero INT NOT NULL,
    Projlocal VARCHAR,
    Dnum INT,
    PRIMARY KEY(Projnumero),
    FOREIGN KEY(Dnum) REFERENCES DEPARTAMENTO(Dnumero)
);

CREATE TABLE TRABALHA_EM (
    Fcpf CHAR(11) UNIQUE NOT NULL,
    Pnr INT,
    Horas INT,
    PRIMARY KEY(Fcpf, Pnr),
    FOREIGN KEY(Fcpf) REFERENCES FUNCIONARIO(Cpf),
    FOREIGN KEY(Pnr) REFERENCES PROJETO(Projnumero)
);

CREATE TABLE DEPENDENTE (
    Fcpf CHAR(11) UNIQUE NOT NULL,
    Nome_dependente VARCHAR NOT NULL,
    Sexo CHAR(1),
    Data_nasc DATE,
    Parentesco VARCHAR,
    PRIMARY KEY(Fcpf, Nome_dependente),
    FOREIGN KEY(Fcpf) REFERENCES FUNCIONARIO(Cpf)
);

